---
- name: "Bootstrap SSL Files"
  hosts: "all"
  gather_facts: true
  remote_user: root
  strategy: free
  become: true
  become_method: sudo
  become_user: root

  tasks:

    - name: "Include tool.bootstrap_ssl_files"
      tags:
        - "tool.bootstrap_ssl_files"
      vars:
        bootstrap_ssl_files_user: "{{ input_bootstrap_ssl_files_user }}"
        bootstrap_ssl_files_base_path: "{{ input_bootstrap_ssl_files_base_path }}"
        bootstrap_ssl_files_ca_validity: "{{ input_bootstrap_ssl_files_ca_validity }}"
        bootstrap_ssl_files_key_size: "{{ input_bootstrap_ssl_files_key_size }}"
        bootstrap_ssl_files_root_ca: "{{ input_bootstrap_ssl_files_root_ca }}"
        bootstrap_ssl_files_intermediates_ca: "{{ input_bootstrap_ssl_files_intermediates_ca }}"
        bootstrap_ssl_files_end_certs: "{{ input_bootstrap_ssl_files_end_certs }}"
        bootstrap_ssl_files_cert_validity: "{{ input_bootstrap_ssl_files_cert_validity }}"
      ansible.builtin.include_role:
        name: "tool.bootstrap_ssl_files"
