---
- name: "Bootstrap Ansible SSL Files"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_user: root

  tasks:

    - name: "Include tool.bootstrap_ssl_files"
      tags:
        - "tool.bootstrap_ssl_files"
      vars:
        bootstrap_ssl_files__user: "{{ input_bootstrap_ssl_files__user }}"
        bootstrap_ssl_files__base_path: "{{ input_bootstrap_ssl_files__base_path }}"
        bootstrap_ssl_files__ca_validity: "{{ input_bootstrap_ssl_files__ca_validity }}"
        bootstrap_ssl_files__key_size: "{{ input_bootstrap_ssl_files__key_size }}"
        bootstrap_ssl_files__root_ca: "{{ input_bootstrap_ssl_files__root_ca }}"
        bootstrap_ssl_files__intermediates_ca: "{{ input_bootstrap_ssl_files__intermediates_ca }}"
        bootstrap_ssl_files__end_certs: "{{ input_bootstrap_ssl_files__end_certs }}"
        bootstrap_ssl_files__cert_validity: "{{ input_bootstrap_ssl_files__cert_validity }}"
      ansible.builtin.include_role:
        name: "tool.bootstrap_ssl_files"
